server:
  port: 10086
  context-path: /kachiManagerment

spring:
  profiles:
    active: dev
  ##把数据库日期格式转换成json返回页面的格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize:  5
    minIdle:  5
    maxActive:  20
    maxWait:  60000
    timeBetweenEvictionRunsMillis:  60000
    minEvictableIdleTimeMillis: 60000
    validationQuery:  SELECT 1 from dual
    testWhileIdle:  true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize:  20

  thymeleaf:
    prefix: classpath:/static/site/
    suffix: .html
  # 上传文件设置
  http:
    multipart:
      #单个文件最大
      max-file-size: 50MB
      #总上传数据总大小
      max-request-size: 50MB

#spring-boot整合mybatis
mybatis:
  #config-location: classpath:/mapper/config/mybatisConfig.xml #可以注射掉,没用到该配置文件
  mapper-locations: classpath:/mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

filter:
  noFilterPath: .css;.js;.png;.jpg;gif;verificationCode;login.html;login;logout;error404.html;getCode;q;interface;download;getPublicKey;personal;background/.*

sendWiFiPass: 88888888
isStatTerminal: true

#memcached缓存配置
memcache:
  initConn: 15
  minConn:  10
  maxConn:  100
  maintSleep: 30
  nagle:  false
  maxIdle:  6000
  socketTO: 30000
  socketConnectTO:  0
  aliveCheck: true
  failback: true
  failover: true

aliyun:
  accessKey:  LTAIXlpkOgjoa4h6
  accessSecurity: 6QCw9x8aPkpGBrxfK6UTh7ybc73pmL
logging:
  level:
    com.team.dao: debug




